# Generated by Django 4.0.5 on 2022-07-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_alter_song_album_alter_song_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.CharField(default=0, max_length=1500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='language',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Malayalam', 'Malayalam')], max_length=20),
        ),
    ]
