# Generated by Django 4.0.5 on 2022-07-05 17:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicapp', '0009_artist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artist',
            new_name='Comments',
        ),
    ]
