# Generated by Django 4.0.5 on 2022-07-06 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0012_alter_comments_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='song',
        ),
    ]
