# Generated by Django 4.0.5 on 2022-07-06 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0016_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comments',
        ),
    ]
